[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stable_sol = "8yY7WqCf3jy9DJTBYV7Dj1MpRrF69V5jvEkKTNTH4HaL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
